language: go
go:
    - "1.10.x"
    - master
addons:
  sonarcloud:
    organization: "kori-irrlicht-github"
install:
  - make install
  - make devinstall
script:
  # other script steps might be done before running the actual analysis
  - make test
  - sonar-scanner
